import multiprocessing
import type
import utility

log_level = type.LogLevel.info
project_name = "mapillary-dataset-network"
run_name_baseline = utility.generateRunName("baseline")
run_name_decomposed = utility.generateRunName("decomposed")

config_baseline = {
    "data_loader_batch_size": 32,
    "data_loader_shuffle": True,
    "data_loader_worker_count": multiprocessing.cpu_count(),
    "dataset_dir": "../../mapillary-dataset/images/sliced/original",
    "dataset_split_percentage_train": 0.8,
    "dataset_split_percentage_validation": 0.1,
    "dataset_split_percentage_test": 0.1,
    "dropout_probability": 0.5,
    "dry_run": False,
    "epochs": 35,
    "fine_tuning": True,
    "learning_rate_scheduler_mode": "min",
    "learning_rate_scheduler_factor": 0.1,
    "learning_rate_scheduler_patient": 1,
    "learning_rate_scheduler_threshold": 1e-4,
    "learning_rate_scheduler_threshold_mode": "rel",
    "learning_rate_scheduler_cooldown": 0,
    "learning_rate_scheduler_min_learning_rate": 0,
    "learning_rate_scheduler_min_learning_rate_decay": 1e-8,
    "learning_rate_scheduler_verbose": True,
    "load_best": False,
    "l2_lambda": 1e-3,
    "model_dir": "../model." + run_name_baseline + ".d",
    "model_dir_best": "../model." + run_name_baseline + ".d",
    "model_file_name_accuracy_validation": "accuracy_validation.pth",
    "model_file_name_class_indices_test": "class_indices_test.pth",
    "model_file_name_classes": "classes.pth",
    "model_file_name_criterion": "criterion.pth",
    "model_file_name_data_loader_test": "data_loader_test.pth",
    "model_file_name_data_loader_train": "data_loader_train.pth",
    "model_file_name_data_loader_validation": "data_loader_validation.pth",
    "model_file_name_epoch": "epoch.pth",
    "model_file_name_learning_rate_scheduler": "learning_rate_scheduler.pth",
    "model_file_name_model": "model.pth",
    "model_file_name_model_best": "model_best.pth",
    "model_file_name_optimizer": "optimizer.pth",
    "model_file_name_outputs_test": "outputs_test.pth",
    "model_file_name_statistics_evaluate": "statistics_evaluate.json",
    "model_file_name_statistics_test": "statistics_test.json",
    "model_file_name_statistics_train": "statistics_train.json",
    "model_input_height": 224,
    "model_input_width": 224,
    "model_input_channels": 3,
    "model_pretrained_weights": "IMAGENET1K_V2",
    "optimizer_learning_rate": 1e-3,
    "optimizer_momentum": 0.9,
    "optimizer_weight_decay": 1e-6,
    "use_l2_loss": False
}

config_decomposed = {
    "data_loader_batch_size": 32,
    "data_loader_shuffle": True,
    "data_loader_worker_count": multiprocessing.cpu_count(),
    "dataset_config_file_name": "dataset.json",
    "dataset_delimiter_file_name": "---",
    "dataset_delimiter_label": "--",
    "dataset_dir": "../../mapillary-dataset/images/sliced/generated",
    "dataset_split_percentage_train": 0.8,
    "dataset_split_percentage_validation": 0.1,
    "dataset_split_percentage_test": 0.1,
    "dropout_probability": 0.5,
    "dry_run": False,
    "epochs": 35,
    "fine_tuning": True,
    "learning_rate_scheduler_mode": "min",
    "learning_rate_scheduler_factor": 0.1,
    "learning_rate_scheduler_patient": 1,
    "learning_rate_scheduler_threshold": 1e-4,
    "learning_rate_scheduler_threshold_mode": "rel",
    "learning_rate_scheduler_cooldown": 0,
    "learning_rate_scheduler_min_learning_rate": 0,
    "learning_rate_scheduler_min_learning_rate_decay": 1e-8,
    "learning_rate_scheduler_verbose": True,
    "load_best": False,
    "l2_lambda": 1e-3,
    "model_dir": "../model." + run_name_decomposed + ".d",
    "model_dir_best": "../model." + run_name_decomposed + ".d",
    "model_file_name_accuracy_validation": "accuracy_validation.pth",
    "model_file_name_class_indices_test": "class_indices_test.pth",
    "model_file_name_classes": "classes.pth",
    "model_file_name_criterion": "criterion.pth",
    "model_file_name_data_loader_test": "data_loader_test.pth",
    "model_file_name_data_loader_train": "data_loader_train.pth",
    "model_file_name_data_loader_validation": "data_loader_validation.pth",
    "model_file_name_epoch": "epoch.pth",
    "model_file_name_learning_rate_scheduler": "learning_rate_scheduler.pth",
    "model_file_name_model": "model.pth",
    "model_file_name_model_best": "model_best.pth",
    "model_file_name_optimizer": "optimizer.pth",
    "model_file_name_outputs_test": "outputs_test.pth",
    "model_file_name_statistics_evaluate": "statistics_evaluate.json",
    "model_file_name_statistics_test": "statistics_test.json",
    "model_file_name_statistics_train": "statistics_train.json",
    "model_input_height": 224,
    "model_input_width": 224,
    "model_input_channels": 3,
    "model_pretrained_weights": "IMAGENET1K_V2",
    "optimizer_learning_rate": 1e-3,
    "optimizer_momentum": 0.9,
    "optimizer_weight_decay": 1e-6,
    "use_l2_loss": False
}
